### ISSUE TITLE
Subscribe / Signup Process Issues

### ISSUE THREAD

**Issue by jeremytackett** [kalebheitzman/how2charist#33]
- [x] Submit button doesn't work when adding a new email address to subscribe. Have to press enter to submit.
- [x] Need a "login" or "watch now" button when logging in with an email address and access code.

**Comment by kalebheitzman** [comment]
- Tokens are being generated when a new user signs up and they are.
- Token login works.

One thing to note: If you manually add a user to the list you either have to manually enter an access token or I have to run a script. We don't want to add users manually if at all possible. We want them to go through the signup form.

**Comment by kalebheitzman** [comment]
See #46 for login and watch now button.
